CREATE TABLE IF NOT EXISTS User {
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255) not null,
    email varchar(512) not null,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
};

CREATE TABLE IF NOT EXISTS Item {
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255) not null,
    description text not null,
    owner_id bigint not null,
    available boolean not null,
    CONSTRAINT pk_item PRIMARY KEY (id)
};